[project]
name = "non-parametric-prior"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10, <3.12"
dependencies = [
    "elicito[full]==0.2.0",
    "bayesflow==1.1.6",
    "tensorflow >= 2.14",
    "tensorflow-probability >= 0.23",
]
